### ISSUE TITLE
No emoji for bumping dependency versions

### ISSUE THREAD

**Issue by purinkle** [dannyfritz/commit-message-emoji#33] opened 2018-08-31 11:07 UTC
In Ruby projects we often bump gems and in JavaScript projects we often bump packages.

What would be an appropriate emoji for such a commit?

May I suggest 👊? Is this too aggressive?

**Comment by dannyfritz** [comment] 2018-08-31 14:02
This is a duplicate of #12 

That being said, just because I don't want to add it to the spec, doesn't mean you can't use it, or fork your own.

**Closed by dannyfritz** 2018-08-31 14:02 UTC
